spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MYSQL

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    web:
      pageable:
        default-page-size: 5

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

custom:
  site:
    baseUrl: "http://localhost:8080"
